apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: catalogue-db-dev
spec:
  clusterServiceClassExternalName: atp-service
  clusterServicePlanExternalName: standard
  parameters:
    name: "MuShop Catalogue DB - dev"
    compartmentId: [ Change to your compartment id. e.g.: ocid1.compartment.oc1..aaaaaaa...]
    dbName: cataloguedev
    cpuCount: 1
    storageSizeTBs: 1
    password: s123456789S@
    licenseType: BYOL
    autoScaling: false