# Global service configurations
global:
  ociAuthSecret: oci-credentials  # OCI authentication credentials secret name
  ossStreamSecret: oss-connection # OCI Streaming secret name
  oosBucketSecret: oos-bucket     # Object storage bucket secret name (optional)
  # ATP Secrets
  oadbAdminSecret: oadb-admin           # Name of DB Admin secret created separately
  oadbWalletSecret: oadb-wallet         # Name of wallet secret created separately
  oadbConnectionSecret: oadb-connection # Name of connection secret created separately

ingress:
  enabled: true

api:
  env:
    mediaUrl:                 # URL for catalog image assets
    newsletterSubscribeUrl:   # Newsletter subscription endpoint (https://[API_GATEWAY_URL]/newsletter/subscribe)
 
secrets:
  streams:
    region:           # OCI region for stream instance (eg us-phoenix-1)
    streamId:         # Stream OCID
    streamName:       # Stream name (string)
    compartmentId:    # Compartment ID where stream is provisioned