# Global service configurations
global:
  ociAuthSecret:         # OCI authentication credentials secret name
  ossStreamSecret:       # OCI Streaming secret name
  oosBucketSecret:       # Object storage bucket secret name (optional)
  # ATP Secrets
  oadbAdminSecret:       # Name of DB Admin secret created earlier
  oadbWalletSecret:      # Name of wallet secret created earlier
  oadbConnectionSecret:  # Name of connection secret created earlier

ingress:
  enabled: true

api:
  env:
    mediaUrl:                 # URL for catalog image assets
    newsletterSubscribeUrl:   # Newsletter subscription endpoint (https://[API_GATEWAY_URL]/newsletter/subscribe)
 
secrets:
  streams:
    region:           # OCI region for stream instance
    streamId:         # Stream OCID
    streamName:       # Stream name (string)
    compartmentId:    # Compartment ID where stream is provisioned