# Global service configurations
global:
  ociAuthSecret: oci-credentials  # OCI authentication credentials secret name
  ossStreamSecret: oss-connection # OCI Streaming secret name
  oosBucketSecret: oos-bucket     # Object storage bucket secret name (optional)
  # ATP Secrets
  oadbAdminSecret: oadb-admin           # Name of ATP Admin secret created separately
  oadbWalletSecret: oadb-wallet         # Name of ATP Wallet secret created separately
  oadbConnectionSecret: oadb-connection # Name of ATP Connection secret created separately

# Configure ingress to support host-specific routing, tls, etc. Example:
# 
# ingress:
#   hosts:
#     - yourname.mushop.com

# API environment configurations
api:
  env:
    mediaUrl:                 # URL for catalog image assets (https://objectstorage.[REGION].oraclecloud.com/n/[NAMESPACE]/b/[BUCKET_NAME]/o/)
    newsletterSubscribeUrl:   # Newsletter subscription endpoint (https://[API_GATEWAY_URL]/newsletter/subscribe)

# These options may be used instead of global.ossStreamSecret and global.oosBucketSecret, if desired
secrets:
  streams:
    streamId:           # Stream OCID
    messageEndpoint:    # Stream messsage endpoint URL
  
  bucket:
    region:     # OCI region for bucket (eg us-phoenix-1)
    name:       # Bucket name (string)      
    namespace:  # Object Storage namespace (string)
    par:        # Pre-authenticated bucket request (URL)