# Source: mushop/charts/shipping/templates/shipping-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
    run: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shipping
      run: shipping
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shipping
        run: shipping
    spec:
      containers:
        - name: shipping
          image: "iad.ocir.io/oracle/ateam/mushop-shipping:1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: STREAM_NAME
              value: # <ENTER VALUE>
            - name: STREAM_ID
              value: # <ENTER VALUE>
            - name: OCI_TENANT_ID
              value: # <ENTER VALUE>
            - name: OCI_USER_ID
              value: # <ENTER VALUE>
            - name: OCI_FINGERPRINT
              value: # <ENTER VALUE>
            - name: OCI_PASS_PHRASE
              value: # <ENTER VALUE>
            - name: OCI_API_KEY
              value: # <ENTER VALUE>
            - name: OCI_REGION
              value: # <ENTER VALUE>
            - name: OCI_COMPARTMENT_ID
              value: # <ENTER VALUE>
---
# Source: mushop/charts/shipping/templates/shipping-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels: 
    app.kubernetes.io/name: shipping
    run: shipping
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: shipping
    run: shipping
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
